"""Write results/final_manifest.json (final-kbs protocol, P10).

One machine-readable record of the configuration behind the final paper: commit, artifact
version, dataset hashes, seed windows, window sizes, prevalences, latencies, models,
generators, gates, risk-control levels and spending schedules, the collision counters of the
final leakage-free causal matrix (summed from the raw per-seed logs), label totals, output
pinning, and the audit verdict. Regenerated by `make final-paper`; verified by the tests.
"""
from __future__ import annotations

import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parents[2]
OUT = REPO / "results" / "final_manifest.json"

CORE_DATASETS = [
    "data/raw/cicids2017/MachineLearningCVE/Tuesday-WorkingHours.pcap_ISCX.csv",
    "data/raw/cicids2017/MachineLearningCVE/Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv",
    "data/processed/unsw_nb15/unsw_ref_no_reconnaissance_binary.csv",
    "data/processed/unsw_nb15/unsw_cur_reconnaissance_binary.csv",
    "data/processed/ton_iot_q1_gate/ton_iot_ref_no_scanning_binary.csv",
    "data/processed/ton_iot_q1_gate/ton_iot_cur_scanning_binary.csv",
]


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def git_sha() -> str:
    try:
        return subprocess.run(["git", "rev-parse", "HEAD"], cwd=REPO, capture_output=True,
                              text=True, check=True).stdout.strip()
    except Exception:
        return "unknown"


def artifact_version() -> str:
    bib = (REPO / "manuscript" / "references.bib").read_text(encoding="utf-8")
    m = re.search(r"note\s*=\s*\{Version ([0-9.]+)\}", bib)
    return m.group(1) if m else "unknown"


def causal_matrix_counters() -> dict:
    """Sum the collision/label counters of the final-kbs causal-64 matrix arms."""
    rows = []
    for d in sorted((REPO / "results" / "raw").glob("paper2_fk_*_c64_*")):
        f = d / "paper2_progressive_readaptation_by_seed.csv"
        if not f.exists():
            continue
        s = pd.read_csv(f)
        s = s[s.method != "no_adaptation"]
        rows.append(dict(
            arm=d.name,
            n_seeds=int(s.seed.nunique()),
            probe_row_collisions=int(s.probe_row_collisions.sum()),
            cand_future_collisions=int(s.cand_future_collisions.sum()),
            n_commit_no_probe=int(s.n_commit_no_probe.sum()) if "n_commit_no_probe" in s else None,
            labels_used_total=int(s.labels_used_total.sum()),
            labels_probe=int(s.labels_probe.sum()) if "labels_probe" in s else None,
        ))
    return dict(
        arms=rows,
        total_probe_row_collisions=int(sum(r["probe_row_collisions"] for r in rows)) if rows else None,
        total_cand_future_collisions=int(sum(r["cand_future_collisions"] for r in rows)) if rows else None,
        total_commit_no_probe=int(sum(r["n_commit_no_probe"] or 0 for r in rows)) if rows else None,
    )


def run_audit() -> dict:
    r = subprocess.run([sys.executable, "-m", "src.analysis.audit_paper2_claims"],
                       cwd=REPO, capture_output=True, text=True)
    m = re.search(r"AUDIT: (\d+)/(\d+) checks pass", r.stdout)
    return dict(status="pass" if r.returncode == 0 else "FAIL",
                checks_passed=int(m.group(1)) if m else None,
                checks_total=int(m.group(2)) if m else None)


def main() -> None:
    tables = REPO / "results" / "tables"
    manifest_file = tables / "MANIFEST.sha256"
    payload = dict(
        commit_sha=git_sha(),
        artifact_version=artifact_version(),
        datasets={p: (sha256(REPO / p) if (REPO / p).exists() else "missing")
                  for p in CORE_DATASETS},
        seeds=dict(
            confirmatory_v2="104-133 (30 pristine seeds; smokes on 164/195/226 excluded)",
            temporal_friday="165-194", temporal_wednesday="196-225", temporal_thursday="227-256",
            unsw_chronological="301-330", cicids_tuesday_chronological="401-430",
        ),
        window_sizes=dict(core=128, causal_matrix=64, causal_sensitivity=128, chronological=256),
        prevalences=dict(balanced=0.5, operational=[0.01, 0.05, 0.10]),
        label_latencies=dict(probe=[0, 5, 10, 20], candidate=[0, 5, 20]),
        models=["svc_rbf", "random_forest", "logreg", "mlp"],
        generators=["full_replace", "sliding_window", "ensemble", "ensemble_cal",
                    "cumulative", "replay"],
        gates=["none", "labeled_probe", "labeled_probe_holdout", "labeled_probe_lcb",
               "labeled_probe_mcnemar", "labeled_probe_seq", "labeled_probe_seqav",
               "labeled_probe_cs", "labeled_probe_ebcs", "labeled_probe_strat",
               "labeled_probe_ebcs_strat", "labeled_probe_ebcs_defer",
               "labeled_probe_exact_strat", "vbc_sg", "unsup_disagree", "atc", "doc",
               "two_stage"],
        risk_control=dict(
            per_proposal_alpha_cs=0.10,
            mcnemar_alpha=0.05,
            mcnemar_alpha_sensitivity=0.10,
            lifetime_alpha=0.10,
            lifetime_max_proposals=10,
            alpha_spending_schedules=["bonferroni", "pseries"],
            defer_windows=5,
        ),
        collision_counts=causal_matrix_counters(),
        outputs=dict(
            tables_manifest_sha256=sha256(manifest_file) if manifest_file.exists() else "missing",
            n_table_csvs=len(list(tables.rglob("*.csv"))),
            pdfs=[p for p in ("manuscript/main.pdf", "manuscript/supplement.pdf",
                              "manuscript/main_ieee.pdf") if (REPO / p).exists()],
        ),
        audit=run_audit(),
    )
    OUT.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    cc = payload["collision_counts"]
    print(f"wrote {OUT}")
    print(f"  commit {payload['commit_sha'][:12]}  version {payload['artifact_version']}  "
          f"audit {payload['audit']['checks_passed']}/{payload['audit']['checks_total']} "
          f"({payload['audit']['status']})")
    print(f"  causal-64 collisions: probe={cc['total_probe_row_collisions']} "
          f"cand-future={cc['total_cand_future_collisions']} "
          f"commits-without-probe={cc['total_commit_no_probe']}")


if __name__ == "__main__":
    main()
