"""Write results/final_manifest.json (final-kbs protocol, P10).

One machine-readable record of the configuration behind the final paper: commit, artifact
version, dataset hashes, seed windows, window sizes, prevalences, latencies, models,
generators, gates, risk-control levels and spending schedules, the collision counters of the
final leakage-free causal matrix (summed from the raw per-seed logs), label totals, output
pinning, and the audit verdict. Regenerated by `make final-paper`; verified by the tests.
"""
from __future__ import annotations

import hashlib
import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parents[2]
OUT = REPO / "results" / "final_manifest.json"

# Bump when the manifest's field layout changes so consumers can branch on it.
MANIFEST_SCHEMA_VERSION = "1.1.0"

CORE_DATASETS = [
    "data/raw/cicids2017/MachineLearningCVE/Tuesday-WorkingHours.pcap_ISCX.csv",
    "data/raw/cicids2017/MachineLearningCVE/Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv",
    "data/processed/unsw_nb15/unsw_ref_no_reconnaissance_binary.csv",
    "data/processed/unsw_nb15/unsw_cur_reconnaissance_binary.csv",
    "data/processed/ton_iot_q1_gate/ton_iot_ref_no_scanning_binary.csv",
    "data/processed/ton_iot_q1_gate/ton_iot_cur_scanning_binary.csv",
]


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def git_sha() -> str:
    try:
        return subprocess.run(["git", "rev-parse", "HEAD"], cwd=REPO, capture_output=True,
                              text=True, check=True).stdout.strip()
    except Exception:
        return "unknown"


def artifact_version() -> str:
    bib = (REPO / "manuscript" / "references.bib").read_text(encoding="utf-8")
    m = re.search(r"note\s*=\s*\{Version ([0-9.]+)\}", bib)
    return m.group(1) if m else "unknown"


def causal_matrix_counters() -> dict:
    """Sum the collision/label counters of the final-kbs causal-64 matrix arms."""
    rows = []
    for d in sorted((REPO / "results" / "raw").glob("paper2_fk_*_c64_*")):
        f = d / "paper2_progressive_readaptation_by_seed.csv"
        if not f.exists():
            continue
        s = pd.read_csv(f)
        s = s[s.method != "no_adaptation"]
        rows.append(dict(
            arm=d.name,
            n_seeds=int(s.seed.nunique()),
            probe_row_collisions=int(s.probe_row_collisions.sum()),
            cand_future_collisions=int(s.cand_future_collisions.sum()),
            n_commit_no_probe=int(s.n_commit_no_probe.sum()) if "n_commit_no_probe" in s else None,
            labels_used_total=int(s.labels_used_total.sum()),
            labels_probe=int(s.labels_probe.sum()) if "labels_probe" in s else None,
        ))
    return dict(
        arms=rows,
        total_probe_row_collisions=int(sum(r["probe_row_collisions"] for r in rows)) if rows else None,
        total_cand_future_collisions=int(sum(r["cand_future_collisions"] for r in rows)) if rows else None,
        total_commit_no_probe=int(sum(r["n_commit_no_probe"] or 0 for r in rows)) if rows else None,
    )


def ledger_summary() -> dict:
    """final-q1 Fase A2: the ledger is part of the manifest, so a reviewer can see at a glance
    which blocks feed which manuscript table and whether any is missing."""
    f = REPO / "results" / "final_experiment_ledger.csv"
    if not f.exists():
        return {"status": "missing"}
    L = pd.read_csv(f)
    # M3: surface the orphan-directory check (a final-family raw dir claimed by no block) in
    # the manifest, recomputed from the ledger's own declared scope/superseded rules so the
    # two can never disagree.
    from src.analysis.make_final_experiment_ledger import compute_orphans
    orphans = compute_orphans()
    return dict(path="results/final_experiment_ledger.csv", n_blocks=int(len(L)),
                n_arm_dirs=int(L.n_arm_dirs.sum()),
                missing_blocks=L[L.status == "MISSING"].block_id.tolist(),
                n_orphan_dirs=len(orphans), orphan_dirs=orphans)


def harm_summary() -> dict:
    """final-q1 blocker B: immediate AND deferred commits, with censoring, from the budget
    frontier. The manifest must never let 'zero harmful commits' rest on partial data."""
    f = REPO / "results" / "tables" / "paper2_final_q1" / "budget_frontier.csv"
    if not f.exists():
        return {"status": "missing"}
    B = pd.read_csv(f)
    cols = ("commits_total", "n_commits_immediate", "n_commits_deferred",
            "e6_n_evaluable", "e6_n_censored", "e6_harmful_h5",
            "e6_harmful_immediate", "e6_harmful_deferred")
    if not all(c in B.columns for c in cols):
        return {"status": "stale (rerun make_paper2_q1_frontier)"}
    ev = int(B.e6_n_evaluable.sum()); k = int(B.e6_harmful_h5.sum())
    return dict(commits_total=int(B.commits_total.sum()),
                immediate=int(B.n_commits_immediate.sum()),
                deferred=int(B.n_commits_deferred.sum()),
                evaluable_h5=ev, censored_h5=int(B.e6_n_censored.sum()),
                harmful_h5=k, harmful_immediate=int(B.e6_harmful_immediate.sum()),
                harmful_deferred=int(B.e6_harmful_deferred.sum()),
                harmful_rate_h5=(round(k / ev, 4) if ev else None))


def q1_final_patch_summary() -> dict:
    """v1.20.0 (q1-final-patch): temporal-semantics fix + targeted frontier rerun, computed
    from the per-arm run_config.json provenance the committed driver writes -- never typed in.
    """
    raw = REPO / "results" / "raw"
    fresh = reused = 0
    for rc in sorted(raw.glob("q1fc_*/run_config.json")):
        try:
            payload = json.loads(rc.read_text(encoding="utf-8"))
        except Exception:
            continue
        if payload.get("reused_from_v1_19_1"):
            reused += 1
        else:
            fresh += 1
    return dict(
        temporal_semantics="commit resolved at t serves from t+1 (immediate and deferred alike)",
        frontier_driver="src/experiments/run_q1_budget_frontier.py",
        frontier_config="configs/q1_budget_frontier_v2.json",
        frontier_expected_arms=99,
        frontier_arm_breakdown=("90 risk-controlled cells (3 scenarios x 3 policies x 5 caps "
                                "x 2 schedules) + 9 anchors (3 scenarios x {none, point, "
                                "strict})"),
        frontier_rerun_arms=fresh,
        frontier_reused_verified_arms=reused,
        reuse_criterion=("zero deferred commits in the resolution log; provably bit-identical "
                         "under the reorder, validated on three full 30-seed control arms"),
        recovered_driver_sha256=(
            "655309bfec1c01924fd8708b6bde4c2ee055021ba6461959aea5502df11737c7"),
        recovery_report="notes/frontier_driver_recovery_report.md",
        max_served_ba_change_points=0.14,
    )


def run_audit() -> dict:
    r = subprocess.run([sys.executable, "-m", "src.analysis.audit_paper2_claims"],
                       cwd=REPO, capture_output=True, text=True)
    m = re.search(r"AUDIT: (\d+)/(\d+) checks pass", r.stdout)
    return dict(status="pass" if r.returncode == 0 else "FAIL",
                checks_passed=int(m.group(1)) if m else None,
                checks_total=int(m.group(2)) if m else None)


def main() -> None:
    tables = REPO / "results" / "tables"
    manifest_file = tables / "MANIFEST.sha256"
    payload = dict(
        manifest_schema_version=MANIFEST_SCHEMA_VERSION,
        generated_at_utc=datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        # This is the SOURCE commit the manifest describes: git HEAD at generation time, which
        # is necessarily the PARENT of the commit that will seal this file (a file cannot carry
        # the hash of the commit that adds it). The release commit's SHA is recorded AFTER the
        # commit/tag as `release_commit_sha` in a separate release_manifest.json (or the release
        # notes/assets), never here. Do not assert source_commit_sha == HEAD after committing.
        source_commit_sha=git_sha(),
        source_commit_sha_note=(
            "git HEAD when this manifest was generated -- the source commit it describes, and "
            "the parent of the sealing commit. The release SHA is stamped post-tag as "
            "release_commit_sha in release_manifest.json / the release notes, not in this file."),
        artifact_version=artifact_version(),
        datasets={p: (sha256(REPO / p) if (REPO / p).exists() else "missing")
                  for p in CORE_DATASETS},
        seeds=dict(
            confirmatory_v2="104-133 (30 pristine seeds; smokes on 164/195/226 excluded)",
            temporal_friday="165-194", temporal_wednesday="196-225", temporal_thursday="227-256",
            unsw_chronological="301-330", cicids_tuesday_chronological="401-430",
            # final-q1 (all fresh; smokes 499/599/699/1999 excluded from every window)
            q1_budget_frontier="501-530", q1_chronological_matrix="601-630",
            # M1: the reported operational e2e table is the dual-sample (blocker D) arm on
            # seeds 801-830; 701-730 was the single-sample pilot. Kept in sync with the ledger.
            q1_operational_e2e="801-830 (pilot 701-730)",
            q1_ab_confirmatory="2001-2100 (pilot 104-133)",
        ),
        acquisition_policies=["random", "alert_enriched", "disagreement", "hybrid"],
        chronological_streams=[
            "tue_wedthufri", "wed_fri", "thu_fri", "wed_intraday", "thu_intraday",
            "unsw_20", "unsw_40",
        ],
        window_sizes=dict(core=128, causal_matrix=64, causal_sensitivity=128, chronological=256),
        # final-q1: 0.005 belongs here -- it is the lowest prevalence the operational
        # simulation actually runs, and the cell where random inspection is most punishing.
        prevalences=dict(balanced=0.5, operational=[0.005, 0.01, 0.05, 0.10]),
        label_latencies=dict(probe=[0, 5, 10, 20], candidate=[0, 5, 20]),
        models=["svc_rbf", "random_forest", "logreg", "mlp"],
        generators=["full_replace", "sliding_window", "ensemble", "ensemble_cal",
                    "cumulative", "replay"],
        gates=["none", "labeled_probe", "labeled_probe_holdout", "labeled_probe_lcb",
               "labeled_probe_mcnemar", "labeled_probe_seq", "labeled_probe_seqav",
               "labeled_probe_cs", "labeled_probe_ebcs", "labeled_probe_strat",
               "labeled_probe_ebcs_strat", "labeled_probe_ebcs_defer",
               "labeled_probe_exact_strat", "vbc_sg", "unsup_disagree", "atc", "doc",
               "two_stage"],
        risk_control=dict(
            per_proposal_alpha_cs=0.10,
            mcnemar_alpha=0.05,
            mcnemar_alpha_sensitivity=0.10,
            lifetime_alpha=0.10,
            lifetime_max_proposals=10,
            alpha_spending_schedules=["bonferroni", "pseries"],
            defer_windows=5,
            vbc_defer_modes=["accumulate", "cohort", "refresh"],
            accumulate_mode_guarantee="weak conditional null (Proposition 1; supplement S4)",
        ),
        training_delay_windows=[0, 5],
        evidence_tiers=["registered confirmatory core", "registered follow-ups",
                        "causal/operational feasibility", "external boundary (chronological)",
                        "exploratory"],
        collision_counts=causal_matrix_counters(),
        experiment_ledger=ledger_summary(),
        harmful_commits=harm_summary(),
        # q1-final-patch (v1.20.0): the deferred-commit temporal fix and its frontier rerun.
        q1_final_patch=q1_final_patch_summary(),
        outputs=dict(
            tables_manifest_sha256=sha256(manifest_file) if manifest_file.exists() else "missing",
            n_table_csvs=len(list(tables.rglob("*.csv"))),
            pdfs=[p for p in ("manuscript/main.pdf", "manuscript/supplement.pdf",
                              "manuscript/main_ieee.pdf") if (REPO / p).exists()],
        ),
        audit=run_audit(),
    )
    OUT.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    cc = payload["collision_counts"]
    print(f"wrote {OUT}")
    print(f"  source-commit {payload['source_commit_sha'][:12]}  version {payload['artifact_version']}  "
          f"audit {payload['audit']['checks_passed']}/{payload['audit']['checks_total']} "
          f"({payload['audit']['status']})")
    print(f"  causal-64 collisions: probe={cc['total_probe_row_collisions']} "
          f"cand-future={cc['total_cand_future_collisions']} "
          f"commits-without-probe={cc['total_commit_no_probe']}")


if __name__ == "__main__":
    main()
