"""Write results/final_manifest.json (final-kbs protocol, P10).

One machine-readable record of the configuration behind the final paper: commit, artifact
version, dataset hashes, seed windows, window sizes, prevalences, latencies, models,
generators, gates, risk-control levels and spending schedules, the collision counters of the
final leakage-free causal matrix (summed from the raw per-seed logs), label totals, output
pinning, and the audit verdict. Regenerated by `make final-paper`; verified by the tests.
"""
from __future__ import annotations

import hashlib
import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parents[2]
OUT = REPO / "results" / "final_manifest.json"

# Bump when the manifest's field layout changes so consumers can branch on it.
MANIFEST_SCHEMA_VERSION = "1.1.0"

CORE_DATASETS = [
    "data/raw/cicids2017/MachineLearningCVE/Tuesday-WorkingHours.pcap_ISCX.csv",
    "data/raw/cicids2017/MachineLearningCVE/Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv",
    "data/processed/unsw_nb15/unsw_ref_no_reconnaissance_binary.csv",
    "data/processed/unsw_nb15/unsw_cur_reconnaissance_binary.csv",
    "data/processed/ton_iot_q1_gate/ton_iot_ref_no_scanning_binary.csv",
    "data/processed/ton_iot_q1_gate/ton_iot_cur_scanning_binary.csv",
]


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def git_sha() -> str:
    try:
        return subprocess.run(["git", "rev-parse", "HEAD"], cwd=REPO, capture_output=True,
                              text=True, check=True).stdout.strip()
    except Exception:
        return "unknown"


def artifact_version() -> str:
    bib = (REPO / "manuscript" / "references.bib").read_text(encoding="utf-8")
    m = re.search(r"note\s*=\s*\{Version ([0-9.]+)\}", bib)
    return m.group(1) if m else "unknown"


def symmetric_replication_v1_21_summary() -> dict:
    """v1.21.0: the preregistered symmetric-pipeline dynamic replication, read from the
    frozen analysis outputs so the manifest can never drift from them."""
    import json as _json
    import pandas as pd
    sp = REPO / "results" / "tables" / "symmetric_pipeline_dynamic_001"
    con = pd.read_csv(sp / "paired_contrasts.csv")
    sec = pd.read_csv(sp / "security_metrics.csv")
    rc = pd.read_csv(sp / "run_completion.csv")
    ci = _json.loads((sp / "CLAIM_INTERPRETATION.json").read_text(encoding="utf-8"))

    def eff(name):
        r = con[con.contrast == name].iloc[0]
        return dict(effect_pp=float(r.effect_pp), ci95=[float(r.ci95_lo), float(r.ci95_hi)])

    uzs = sec[(sec.scenario == "unsw_zero") & (sec.policy == "strict")
              & (sec.transformer_policy == "own_transformer_per_model")].iloc[0]
    cfg = (REPO / "configs" / "symmetric_pipeline_dynamic_v1.json").read_bytes()
    pages = {}
    try:
        import pypdf
        for p in ("main.pdf", "supplement.pdf", "main_ieee.pdf"):
            pages[p] = len(pypdf.PdfReader(REPO / "manuscript" / p).pages)
    except Exception:
        pages = "pypdf unavailable"
    return dict(
        title=("Validate Before Commit: Candidate Governance for Drift-Triggered "
               "Classifier Pipelines in Network Intrusion Detection"),
        scenario=ci["scenario"],
        decision_rules="protocol Appendix A (frozen pre-run; BA classifies, recall/FPR "
                       "restrict language)",
        transformer_policies=["frozen_initial_transformer", "own_transformer_per_model"],
        detector_transform_policy="frozen_initial (both policies)",
        protocol_commits=dict(protocol="88385660edd8", appendix_a="96576bb",
                              rewrite_protocol="3d1d9f6", sealing_protocol="4658d66"),
        config_sha256=hashlib.sha256(cfg).hexdigest(),
        confirmatory_seeds="3001-3030",
        expected_arms=42, completed_arms=int(rc.complete.sum()),
        frozen_mode_parity="bit-identical vs published v1.20.2 arms (4 arms x 30 seeds; "
                           "parity_report.json per arm)",
        full_drift_own_naive_vs_never=dict(
            ps_full=eff("ps_full: own-naive vs never"),
            unsw_full=eff("unsw_full: own-naive vs never"),
            ton_full=eff("ton_full: own-naive vs never")),
        ownership_interaction_own_vs_frozen_naive=dict(
            ps_full=eff("ps_full: own-naive vs frozen-naive"),
            unsw_full=eff("unsw_full: own-naive vs frozen-naive"),
            ton_full=eff("ton_full: own-naive vs frozen-naive")),
        zero_drift_own_naive_vs_never=dict(
            ps_zero=eff("ps_zero: own-naive vs never"),
            unsw_zero=eff("unsw_zero: own-naive vs never"),
            ton_zero=eff("ton_zero: own-naive vs never")),
        zero_drift_gate_contrasts_all_positive_holm_significant=True,
        statistical_families=dict(F1=3, F2=3, F3=6, F4=12, correction="Holm within family",
                                  test="deterministic centered paired bootstrap (100k)"),
        margins=dict(ba_equivalence_pp=0.5, ba_sensitivities=[0.2, 1.0],
                     recall_NI_pp=1.0, fpr_NI_pp=0.5),
        security_guardrails=dict(
            unsw_zero_strict=dict(
                d_recall_pp=float(uzs.d_recall_vs_naive_pp),
                recall_onesided_lo95=float(uzs.recall_onesided_lo95),
                recall_NI_principal=bool(uzs.recall_NI_principal),
                recall_NI_lax=bool(uzs.recall_NI_lax),
                fpr_NI_principal=bool(uzs.fpr_NI_principal),
                language="trade-off only; no security-improvement language"),
            all_other_winning_cells="pass both preregistered NI margins"),
        harmful_future_value_caveat=(
            "descriptive fractions of future-negative committed proposals within the "
            "controlled trajectories; commits cluster within seeds; no independence "
            "assumed; no population prevalence or deployment probability inferred"),
        qk_vbcsg_scope=("QK-ZZ, VBC-SG/budget frontier and mild drift remain evaluated "
                        "under the historical frozen-transformer policy; no transfer to "
                        "own-transformer pipelines is claimed"),
        chronological_net_harm="unobserved across 13 replays (unchanged; principal "
                               "external-validity limit)",
        experiments_added="symmetric-pipeline dynamic replication (42-arm registered matrix)",
        experiments_rerun_after_frozen_protocol="exactly the registered 42-arm matrix, "
                                                "seeds 3001-3030",
        unregistered_experiments="none",
        v1_20_2_raw_outputs="unchanged (MANIFEST re-pin additive 164->173)",
        manuscript_pages=pages,
    )


def size_matched_control_v1_22_summary() -> dict:
    """v1.22.0 candidate: the preregistered size-matched self-contained challenger control,
    read from the frozen analysis outputs so the manifest can never drift from them."""
    import json as _json
    import pandas as pd
    sm = REPO / "results" / "tables" / "size_matched_own_transformer_001"
    con = pd.read_csv(sm / "paired_contrasts.csv")
    eqv = pd.read_csv(sm / "equivalence.csv")
    desc = pd.read_csv(sm / "descriptive_contrasts.csv")
    rc = pd.read_csv(sm / "run_completion.csv")
    ci = _json.loads((sm / "CLAIM_INTERPRETATION.json").read_text(encoding="utf-8"))
    cfg = (REPO / "configs" / "size_matched_own_transformer_v1.json").read_bytes()

    def eff(name):
        r = con[con.contrast == name].iloc[0]
        return dict(effect_pp=float(r.effect_pp), ci95=[float(r.ci95_lo), float(r.ci95_hi)])

    def deff(name):
        r = desc[desc.contrast == name].iloc[0]
        return dict(effect_pp=float(r.effect_pp), ci95=[float(r.ci95_lo), float(r.ci95_hi)])

    def eq(name):
        e = eqv[(eqv.contrast == name) & (eqv.margin_kind == "primary")].iloc[0]
        return bool(e.equivalent)

    return dict(
        title=("Validate Before Commit: A Controlled Study of Pipeline Construction, "
               "Evidence Asymmetry, and Candidate Promotion in Network Intrusion Detection"),
        registered_outcome=ci["outcome"],
        outcome_note=("ATTENUATION under the frozen P/A/E rules: E1+E2 equivalence pass; "
                      "the preregistered sign-based H5 future-value criterion (E3) blocks "
                      "formal ELIMINATION; substantively, size matching neutralizes the "
                      "mean zero-drift harm (mean H5 future value ~0 at the matched size); "
                      "never retro-classified"),
        protocol_commits=dict(protocol="114513f8613d", freeze="c4df062",
                              rewrite_protocol="c7fca9d"),
        config_sha256=hashlib.sha256(cfg).hexdigest(),
        confirmatory_seeds="4001-4030",
        smoke_seeds="4401-4402",
        expected_arms=21, completed_arms=int(rc.complete.sum()),
        nesting=("batch_512 == first 512 rows/class of batch_2000 at every proposal; "
                 "999 (seed, window) pairs verified; 512 path bit-identical to v1.21.0 "
                 "(5/5 CSVs BIT_IDENTICAL in the parity run, seeds 4242-4243)"),
        zero_drift_naive512_vs_never=dict(
            ps_zero=deff("ps_zero: naive-512 vs never"),
            unsw_zero=deff("unsw_zero: naive-512 vs never"),
            ton_zero=deff("ton_zero: naive-512 vs never")),
        zero_drift_naive2000_vs_never=dict(
            ps_zero=dict(**eff("ps_zero: naive-2000 vs never"),
                         equivalent_pm0p5=eq("ps_zero: naive-2000 vs never")),
            unsw_zero=dict(**eff("unsw_zero: naive-2000 vs never"),
                           equivalent_pm0p5=eq("unsw_zero: naive-2000 vs never")),
            ton_zero=dict(**eff("ton_zero: naive-2000 vs never"),
                          equivalent_pm0p5=eq("ton_zero: naive-2000 vs never"))),
        candidate_size_effect_naive2000_vs_naive512=dict(
            ps_zero=eff("ps_zero: naive-2000 vs naive-512"),
            unsw_zero=eff("unsw_zero: naive-2000 vs naive-512"),
            ton_zero=eff("ton_zero: naive-2000 vs naive-512")),
        gate_value_at_2000="0/6 Holm-significant; all effects < 0.14 pp; all six "
                           "CI90-equivalent to naive within +-0.5 pp",
        guardrails="all six matched-size gate cells pass recall/FPR NI; unsw strict_512 "
                   "recall-NI failure replicates (trade-off language only)",
        statistical_families=dict(F1=3, F2=3, F3=6, F4=6, correction="Holm within family",
                                  test="deterministic centered paired bootstrap (100k)"),
        future_negative_signs_caveat=(
            "descriptive within-trajectory sign fractions over seed-clustered commits; "
            "near-50% rates at the matched size around a ~0 mean; no population "
            "prevalence, deployment probability or binomial bound inferred"),
        scope=("zero drift only; random proposal trigger; balanced pools; own-transformer "
               "only; full-drift size-matched, observed-data size-matched and VBC-SG under "
               "size-matched own pipelines NOT evaluated"),
        v1_21_0_artifact="unchanged (sealed manifests byte-identical; 173/173 pinned)",
        experiments_added="size-matched own-transformer control (21-arm registered matrix)",
        unregistered_experiments="none",
    )


def causal_matrix_counters() -> dict:
    """Sum the collision/label counters of the final-kbs causal-64 matrix arms."""
    rows = []
    for d in sorted((REPO / "results" / "raw").glob("paper2_fk_*_c64_*")):
        f = d / "paper2_progressive_readaptation_by_seed.csv"
        if not f.exists():
            continue
        s = pd.read_csv(f)
        s = s[s.method != "no_adaptation"]
        rows.append(dict(
            arm=d.name,
            n_seeds=int(s.seed.nunique()),
            probe_row_collisions=int(s.probe_row_collisions.sum()),
            cand_future_collisions=int(s.cand_future_collisions.sum()),
            n_commit_no_probe=int(s.n_commit_no_probe.sum()) if "n_commit_no_probe" in s else None,
            labels_used_total=int(s.labels_used_total.sum()),
            labels_probe=int(s.labels_probe.sum()) if "labels_probe" in s else None,
        ))
    return dict(
        arms=rows,
        total_probe_row_collisions=int(sum(r["probe_row_collisions"] for r in rows)) if rows else None,
        total_cand_future_collisions=int(sum(r["cand_future_collisions"] for r in rows)) if rows else None,
        total_commit_no_probe=int(sum(r["n_commit_no_probe"] or 0 for r in rows)) if rows else None,
    )


def ledger_summary() -> dict:
    """final-q1 Fase A2: the ledger is part of the manifest, so a reviewer can see at a glance
    which blocks feed which manuscript table and whether any is missing."""
    f = REPO / "results" / "final_experiment_ledger.csv"
    if not f.exists():
        return {"status": "missing"}
    L = pd.read_csv(f)
    # M3: surface the orphan-directory check (a final-family raw dir claimed by no block) in
    # the manifest, recomputed from the ledger's own declared scope/superseded rules so the
    # two can never disagree.
    from src.analysis.make_final_experiment_ledger import compute_orphans
    orphans = compute_orphans()
    return dict(path="results/final_experiment_ledger.csv", n_blocks=int(len(L)),
                n_arm_dirs=int(L.n_arm_dirs.sum()),
                missing_blocks=L[L.status == "MISSING"].block_id.tolist(),
                n_orphan_dirs=len(orphans), orphan_dirs=orphans)


def harm_summary() -> dict:
    """final-q1 blocker B: immediate AND deferred commits, with censoring, from the budget
    frontier. The manifest must never let 'zero harmful commits' rest on partial data."""
    f = REPO / "results" / "tables" / "paper2_final_q1" / "budget_frontier.csv"
    if not f.exists():
        return {"status": "missing"}
    B = pd.read_csv(f)
    cols = ("commits_total", "n_commits_immediate", "n_commits_deferred",
            "e6_n_evaluable", "e6_n_censored", "e6_harmful_h5",
            "e6_harmful_immediate", "e6_harmful_deferred")
    if not all(c in B.columns for c in cols):
        return {"status": "stale (rerun make_paper2_q1_frontier)"}
    ev = int(B.e6_n_evaluable.sum()); k = int(B.e6_harmful_h5.sum())
    # q1-final-patch v1.20.1 (Block A): the H5-evaluable commits are clustered within shared
    # seeds, scenarios and policy/cap/schedule cells, so the 0/506 count is reported as a
    # factual observation only -- no binomial population-rate bound is inferred from it.
    return dict(commits_total=int(B.commits_total.sum()),
                immediate=int(B.n_commits_immediate.sum()),
                deferred=int(B.n_commits_deferred.sum()),
                evaluable_h5=ev, censored_h5=int(B.e6_n_censored.sum()),
                harmful_h5=k, harmful_immediate=int(B.e6_harmful_immediate.sum()),
                harmful_deferred=int(B.e6_harmful_deferred.sum()),
                observed_harmful_proportion_h5=(round(k / ev, 4) if ev else None),
                binomial_upper_bound_reported=False,
                reason=("commit outcomes are clustered within shared seeds, scenarios and "
                        "policy configurations; they are not independent Bernoulli trials"))


def q1_final_patch_summary() -> dict:
    """v1.20.0 (q1-final-patch): temporal-semantics fix + targeted frontier rerun, computed
    from the per-arm run_config.json provenance the committed driver writes -- never typed in.
    """
    raw = REPO / "results" / "raw"
    fresh = reused = 0
    for rc in sorted(raw.glob("q1fc_*/run_config.json")):
        try:
            payload = json.loads(rc.read_text(encoding="utf-8"))
        except Exception:
            continue
        if payload.get("reused_from_v1_19_1"):
            reused += 1
        else:
            fresh += 1
    return dict(
        temporal_semantics="commit resolved at t serves from t+1 (immediate and deferred alike)",
        frontier_driver="src/experiments/run_q1_budget_frontier.py",
        frontier_config="configs/q1_budget_frontier_v2.json",
        frontier_expected_arms=99,
        frontier_arm_breakdown=("90 risk-controlled cells (3 scenarios x 3 policies x 5 caps "
                                "x 2 schedules) + 9 anchors (3 scenarios x {none, point, "
                                "strict})"),
        frontier_rerun_arms=fresh,
        frontier_reused_verified_arms=reused,
        reuse_criterion=("zero deferred commits in the resolution log; provably bit-identical "
                         "under the reorder, validated on three full 30-seed control arms"),
        recovered_driver_sha256=(
            "655309bfec1c01924fd8708b6bde4c2ee055021ba6461959aea5502df11737c7"),
        recovery_report="docs/SCIENTIFIC_PROVENANCE.md",
        max_served_ba_change_points=0.14,
    )


def editorial_v1202_summary() -> dict:
    """v1.20.2: editorial-compression facts. The 'before' word count is the frozen v1.20.1
    baseline (measured identically); 'after' is computed live from main.tex."""
    t = (REPO / "manuscript" / "main.tex").read_text(encoding="utf-8")
    body = t[t.find(r"\begin{abstract}"):]
    after = len(re.findall(r"\b[\w'-]+\b", body))
    before = 19413
    return dict(
        editorial_compression=True,
        claim_scope_hardening=True,
        causal_language_removed=True,
        scientific_experiments_rerun=False,
        primary_results_changed=False,
        scientific_csvs_changed=False,
        article_word_count_before=before,
        article_word_count_after=after,
        article_word_reduction_pct=round(100.0 * (before - after) / before, 1),
    )


def statistical_inference_summary() -> dict:
    """v1.20.1: multiplicity + claim-scope facts, computed from the shipped CSVs."""
    out = dict(status="missing")
    mf = REPO / "results" / "tables" / "paper2_final_q1" / "multiplicity.csv"
    cf = REPO / "results" / "tables" / "paper2_final_q1" / "claim_scope_audit.csv"
    if not mf.exists():
        return out
    m = pd.read_csv(mf)
    fam = {f: int(n) for f, n in m.groupby("family").size().items()}
    surv = {f: int(g.significant_adj.sum()) for f, g in m.groupby("family")}
    out = dict(
        multiplicity_method=("deterministic centered paired bootstrap test "
                             "(H0-centered resampling, Monte-Carlo corrected)"),
        bootstrap_resamples=100_000,
        multiplicity_total=int(len(m)),
        family_sizes=fam,
        family_survivors_adj=surv,
        normal_approximation_fallbacks=int(
            (~m.p_method.str.contains("centered paired bootstrap")).sum()),
        sensitivities=["paired t-test", "Wilcoxon signed-rank"],
        harm_population_rate_bound_removed=True,
    )
    if cf.exists():
        a = pd.read_csv(cf)
        out["claim_scope_audit_claims"] = int(len(a))
        out["claim_scope_audit_failures"] = int(a.status.str.startswith("FAIL").sum())
    return out


def run_audit() -> dict:
    r = subprocess.run([sys.executable, "-m", "src.analysis.audit_paper2_claims"],
                       cwd=REPO, capture_output=True, text=True)
    m = re.search(r"AUDIT: (\d+)/(\d+) checks pass", r.stdout)
    return dict(status="pass" if r.returncode == 0 else "FAIL",
                checks_passed=int(m.group(1)) if m else None,
                checks_total=int(m.group(2)) if m else None)


def main(out: Path | None = None) -> None:
    """Write the manifest to `out` (default: the sealed results/final_manifest.json).

    `out` exists so tests can exercise this generator WITHOUT mutating the sealed,
    version-controlled artifact (symmetric-pipeline confirmatory phase fix)."""
    out = OUT if out is None else Path(out)
    tables = REPO / "results" / "tables"
    manifest_file = tables / "MANIFEST.sha256"
    payload = dict(
        manifest_schema_version=MANIFEST_SCHEMA_VERSION,
        generated_at_utc=datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        # This is the SOURCE commit the manifest describes: git HEAD at generation time, which
        # is necessarily the PARENT of the commit that will seal this file (a file cannot carry
        # the hash of the commit that adds it). The release commit's SHA is recorded AFTER the
        # commit/tag as `release_commit_sha` in a separate release_manifest.json (or the release
        # notes/assets), never here. Do not assert source_commit_sha == HEAD after committing.
        source_commit_sha=git_sha(),
        source_commit_sha_note=(
            "git HEAD when this manifest was generated -- the source commit it describes, and "
            "the parent of the sealing commit. The release SHA is stamped post-tag as "
            "release_commit_sha in release_manifest.json / the release notes, not in this file."),
        artifact_version=artifact_version(),
        datasets={p: (sha256(REPO / p) if (REPO / p).exists() else "missing")
                  for p in CORE_DATASETS},
        seeds=dict(
            confirmatory_v2="104-133 (30 pristine seeds; smokes on 164/195/226 excluded)",
            temporal_friday="165-194", temporal_wednesday="196-225", temporal_thursday="227-256",
            unsw_chronological="301-330", cicids_tuesday_chronological="401-430",
            # final-q1 (all fresh; smokes 499/599/699/1999 excluded from every window)
            q1_budget_frontier="501-530", q1_chronological_matrix="601-630",
            # M1: the reported operational e2e table is the dual-sample (blocker D) arm on
            # seeds 801-830; 701-730 was the single-sample pilot. Kept in sync with the ledger.
            q1_operational_e2e="801-830 (pilot 701-730)",
            q1_ab_confirmatory="2001-2100 (pilot 104-133)",
        ),
        acquisition_policies=["random", "alert_enriched", "disagreement", "hybrid"],
        chronological_streams=[
            "tue_wedthufri", "wed_fri", "thu_fri", "wed_intraday", "thu_intraday",
            "unsw_20", "unsw_40",
        ],
        window_sizes=dict(core=128, causal_matrix=64, causal_sensitivity=128, chronological=256),
        # final-q1: 0.005 belongs here -- it is the lowest prevalence the operational
        # simulation actually runs, and the cell where random inspection is most punishing.
        prevalences=dict(balanced=0.5, operational=[0.005, 0.01, 0.05, 0.10]),
        label_latencies=dict(probe=[0, 5, 10, 20], candidate=[0, 5, 20]),
        models=["svc_rbf", "random_forest", "logreg", "mlp"],
        generators=["full_replace", "sliding_window", "ensemble", "ensemble_cal",
                    "cumulative", "replay"],
        gates=["none", "labeled_probe", "labeled_probe_holdout", "labeled_probe_lcb",
               "labeled_probe_mcnemar", "labeled_probe_seq", "labeled_probe_seqav",
               "labeled_probe_cs", "labeled_probe_ebcs", "labeled_probe_strat",
               "labeled_probe_ebcs_strat", "labeled_probe_ebcs_defer",
               "labeled_probe_exact_strat", "vbc_sg", "unsup_disagree", "atc", "doc",
               "two_stage"],
        risk_control=dict(
            per_proposal_alpha_cs=0.10,
            mcnemar_alpha=0.05,
            mcnemar_alpha_sensitivity=0.10,
            lifetime_alpha=0.10,
            lifetime_max_proposals=10,
            alpha_spending_schedules=["bonferroni", "pseries"],
            defer_windows=5,
            vbc_defer_modes=["accumulate", "cohort", "refresh"],
            accumulate_mode_guarantee="weak conditional null (Proposition 1; supplement S4)",
        ),
        training_delay_windows=[0, 5],
        evidence_tiers=["registered confirmatory core", "registered follow-ups",
                        "causal/operational feasibility", "external boundary (chronological)",
                        "exploratory"],
        collision_counts=causal_matrix_counters(),
        experiment_ledger=ledger_summary(),
        harmful_commits=harm_summary(),
        # q1-final-patch (v1.20.0): the deferred-commit temporal fix and its frontier rerun.
        q1_final_patch=q1_final_patch_summary(),
        # q1-final-patch (v1.20.1): the statistical-inference contract, read from the shipped
        # analysis tables themselves so the manifest can never drift from them.
        statistical_inference=statistical_inference_summary(),
        # v1.20.2: final length reduction + final claim-scope hardening (no science changed).
        editorial_v1_20_2=editorial_v1202_summary(),
        # v1.21.0: the preregistered symmetric-pipeline dynamic replication (Scenario A).
        symmetric_replication_v1_21=symmetric_replication_v1_21_summary(),
        # v1.22.0 candidate: the preregistered size-matched control (ATTENUATION).
        size_matched_control_v1_22=size_matched_control_v1_22_summary(),
        # q1-final-patch (v1.20.1, Block C3): the operational acquisition-yield arm's scope,
        # stated field by field so no claim can outrun what the simulation measures.
        operational_arm_scope=dict(
            evaluation_stream_prevalence="balanced",
            detector_calibration_prevalence="balanced",
            candidate_training_sampling="balanced_per_class",
            candidate_training_inspection_cost_modeled=False,
            adjudication_pool_prevalence="operating",
            discovery_sampling_policy=["random", "alert_enriched", "disagreement", "hybrid"],
            discovery_used_for_commit=False,
            validation_sampling_policy="uniform_at_operating_prevalence",
            validation_labels=32,
            decision_metric="plain_accuracy",
            operational_scope="acquisition_yield_and_delay_only",
            end_to_end_pipeline_cost_modeled=False,
        ),
        outputs=dict(
            tables_manifest_sha256=sha256(manifest_file) if manifest_file.exists() else "missing",
            n_table_csvs=len(list(tables.rglob("*.csv"))),
            pdfs=[p for p in ("manuscript/main.pdf", "manuscript/supplement.pdf",
                              "manuscript/main_ieee.pdf") if (REPO / p).exists()],
        ),
        audit=run_audit(),
    )
    out.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    cc = payload["collision_counts"]
    print(f"wrote {out}")
    print(f"  source-commit {payload['source_commit_sha'][:12]}  version {payload['artifact_version']}  "
          f"audit {payload['audit']['checks_passed']}/{payload['audit']['checks_total']} "
          f"({payload['audit']['status']})")
    print(f"  causal-64 collisions: probe={cc['total_probe_row_collisions']} "
          f"cand-future={cc['total_cand_future_collisions']} "
          f"commits-without-probe={cc['total_commit_no_probe']}")


if __name__ == "__main__":
    main()
