"""Regenerate manuscript/main_springer.tex from manuscript/main.tex (Springer svjour3 two-column port).

Target: International Journal of Information Security (Springer Nature). Its submission
guidelines ask for Springer's LaTeX macro package (svjour3) with the ``twocolumn`` option,
numbered references in square brackets, a 150--250 word abstract, 4--6 keywords and a
Statements-and-Declarations block (funding, competing interests, ethics approval, data
availability, author contributions).

``main.tex`` (Elsevier CAS) remains the single source of truth: title, authors, ORCIDs, CRediT
roles, abstract, keywords, body and the funding / competing-interest / data-availability /
generative-AI statements are all read from it. The body transformations are the same as in
``port_ieee.py`` (two-column table variants from ``tables_ieee/``, spanning figures, spanning
verbatim listing), so the three manuscripts cannot diverge in content. No scientific text is
written here; the only text authored by this script is the front-matter plumbing and two
declaration items that Springer requires and the CAS template has no slot for (ethics approval
and code availability), both stated from facts already in the manuscript.

Requires ``svjour3.cls`` and ``svglov3.clo`` in ``manuscript/`` (Springer's LaTeX macro package as
linked from the IJIS submission guidelines) plus ``spmpsci.bst`` (Springer's numbered style for
mathematics/CS journals, which keeps article titles; the ``spphys.bst`` shipped in that zip is
APS-style and omits them).

Usage:  python -m src.analysis.port_springer
Compile: cd manuscript && pdflatex main_springer && bibtex main_springer && pdflatex main_springer && pdflatex main_springer
"""
from __future__ import annotations

import re
from pathlib import Path

MS = Path(__file__).resolve().parents[2] / "manuscript"
JOURNAL = "International Journal of Information Security"

AUTHOR_RE = re.compile(
    r"\\author\[1\]\{(?P<name>.*?)\}\[orcid=(?P<orcid>[\dX-]+)\]\n"
    r"(?P<cor>\\cormark\[1\]\n)?"
    r"\\ead\{(?P<email>.*?)\}\n"
    r"\\credit\{(?P<credit>.*?)\}\n",
    re.S,
)


def _between(text: str, start: str, end: str) -> str:
    return text[text.index(start) + len(start): text.index(end)].strip()


def _short(name: str) -> str:
    """'Roberto Fern\\'andez-Barrios' -> 'R. Fern\\'andez-Barrios' (first token to an initial)."""
    first, rest = name.split(" ", 1)
    return f"{first[0]}. {rest}"


# IJIS: "Refer to the supplementary files as 'Online Resource', e.g. '... additional data are
# given in Online Resource 4'". The supplement is ESM_1.pdf, i.e. Online Resource 1. Wording only;
# the section pointers (S1..S10) are unchanged. main.tex keeps the venue-neutral "Supplementary".
ONLINE_RESOURCE = (
    ("Supplementary~\\S", "Online Resource~1, \\S"),
    ("Supplementary \\S", "Online Resource~1, \\S"),
    ("in the Supplement.", "in Online Resource~1."),
    ("in the Supplement ", "in Online Resource~1 "),
)


def _online_resource(text: str) -> str:
    for old, new in ONLINE_RESOURCE:
        text = text.replace(old, new)
    assert "Supplementary" not in text and "the Supplement" not in text, \
        "an unhandled supplement pointer survived; extend ONLINE_RESOURCE"
    return text


def _replace_once(text: str, old: str, new: str) -> str:
    assert text.count(old) == 1, f"expected exactly one occurrence of {old!r}"
    return text.replace(old, new, 1)


def port_supplement(authors: list[dict], affiliation: str, cor_email: str) -> None:
    """supplement_springer.tex: same body as supplement.tex, with the front page IJIS requires
    for every supplementary file (article title, journal name, author names, affiliation and
    e-mail of the corresponding author) and cross-references resolved against main_springer."""
    sup = (MS / "supplement.tex").read_text(encoding="utf-8")
    sup = _replace_once(sup, "\\externaldocument[][nocite]{main}",
                        "\\externaldocument[][nocite]{main_springer}")
    sup = _replace_once(sup, "\\title{Supplementary Material for\\\\``",
                        "\\title{Online Resource 1 --- Supplementary Material for\\\\``")
    names = [a["name"] for a in authors]
    half = (len(names) + 1) // 2  # two lines of authors: one line overflows article's title width
    sup = _replace_once(
        sup, "\\author{}",
        "\\author{" + ", ".join(names[:half]) + ",\\\\ " + ", ".join(names[half:]) + "\\\\[2pt]"
        "\\small " + affiliation + "\\\\"
        "\\small Corresponding author: " + cor_email + "\\\\[2pt]"
        "\\small Submitted to \\emph{" + JOURNAL + "}}")
    sup = ("%% GENERATED by src/analysis/port_springer.py from supplement.tex -- do not edit by hand.\n"
           "%% Online Resource 1 for the " + JOURNAL + " submission (compile after main_springer).\n"
           + sup)
    (MS / "supplement_springer.tex").write_text(sup, encoding="utf-8", newline="\n")
    print(f"supplement_springer.tex rebuilt from supplement.tex: {len(sup.splitlines())} lines")


def _affiliation(cas: str) -> str:
    block = re.search(r"\\affiliation\[1\]\{(.*?)\}\n\n", cas, re.S).group(1)
    field = lambda k: re.search(k + r"=\{(.*?)\}", block).group(1)  # noqa: E731
    return (f"{field('organization')}, {field('addressline')}, "
            f"{field('postcode')} {field('city')}, {field('country')}")


def main() -> None:
    cas = (MS / "main.tex").read_text(encoding="utf-8")

    # ---- front matter read from main.tex ------------------------------------------------
    title = re.search(r"\\title\[mode=title\]\{(.*?)\}\n", cas, re.S).group(1)
    authors = [m.groupdict() for m in AUTHOR_RE.finditer(cas)]
    assert len(authors) == 4, f"expected 4 authors in main.tex front matter, found {len(authors)}"
    corresponding = [a for a in authors if a["cor"]]
    assert len(corresponding) == 1, "exactly one \\cormark author expected"
    affiliation = _affiliation(cas)
    abstract = re.search(r"\\begin\{abstract\}\n(.*?)\n\\end\{abstract\}", cas, re.S).group(1)
    keywords = [k.strip() for k in
                re.search(r"\\begin\{keywords\}\n(.*?)\n\\end\{keywords\}", cas, re.S)
                .group(1).split("\\sep")]
    assert 4 <= len(keywords) <= 6, f"IJIS asks for 4-6 keywords, main.tex has {len(keywords)}"

    # ---- declarations read from main.tex ------------------------------------------------
    competing = _between(cas, "\\section*{Declaration of competing interest}", "\\section*{Funding}")
    funding = _between(cas, "\\section*{Funding}", "\\section*{Data availability}")
    data = _between(cas, "\\section*{Data availability}",
                    "\\section*{Declaration of generative AI")
    ai_use = _between(
        cas,
        "\\section*{Declaration of generative AI and AI-assisted technologies in the manuscript preparation process}",
        "% CRediT roles are declared",
    )
    contributions = " ".join(f"{a['name']}: {a['credit']}." for a in authors)

    # ---- body: the port_ieee.py transformations + the IJIS "Online Resource" convention ----
    body = cas[cas.index("\\section{Introduction}"):
               cas.index("\\section*{Declaration of competing interest}")]
    body = body.replace("\\input{tables/", "\\input{tables_springer/")
    body = body.replace("\\begin{figure}", "\\begin{figure*}")
    body = body.replace("\\end{figure}", "\\end{figure*}")
    body = body.replace("width=\\linewidth]{docs/img", "width=\\textwidth]{docs/img")
    body = body.replace("\\begin{verbatim}", "\\begin{figure*}[t]\n\\small\n\\begin{verbatim}")
    body = body.replace("\\end{verbatim}", "\\end{verbatim}\n\\end{figure*}")
    body = _online_resource(body)
    # Two-column table variants are the IEEE ones (same measure class); only the wording of the
    # supplement pointers in three captions changes, so they are re-emitted under tables_springer/.
    (MS / "tables_springer").mkdir(exist_ok=True)
    for src in sorted((MS / "tables_ieee").glob("*.tex")):
        (MS / "tables_springer" / src.name).write_text(
            _online_resource(src.read_text(encoding="utf-8")), encoding="utf-8", newline="\n")

    port_supplement(authors, affiliation, corresponding[0]["email"])

    # ---- Springer head ----------------------------------------------------------------------
    names = " \\and ".join(a["name"] for a in authors)
    short_names = " \\and ".join(
        _short(a["name"]) + (" (corresponding author)" if a["cor"] else "") for a in authors)
    emails = "; ".join(a["email"] for a in authors)
    orcids = " $\\cdot$ ".join(f"{_short(a['name'])} {a['orcid']}" for a in authors)
    head = "\n".join([
        "%% Springer svjour3 two-column port -- target: " + JOURNAL + ".",
        "%% GENERATED by src/analysis/port_springer.py from main.tex -- do not edit by hand.",
        "%% Requires svjour3.cls, svglov3.clo, spphys.bst (in this folder; Springer's LaTeX macro",
        "%% package as linked from the IJIS submission guidelines) and figures at ../docs/img/.",
        "\\RequirePackage{fix-cm}",
        "\\documentclass[twocolumn]{svjour3}",
        "\\usepackage[T1]{fontenc}",
        "\\usepackage[utf8]{inputenc}",
        "\\usepackage{mathptmx}",
        "\\usepackage{graphicx}",
        "\\graphicspath{{../}}",
        "\\usepackage{booktabs}",
        "\\usepackage{amsmath,amssymb}",
        "\\usepackage{multirow}",
        "\\usepackage{cite}",
        "\\usepackage[hidelinks]{hyperref}",
        "\\urlstyle{same}",
        "% IJIS asks for DOIs as full links in the reference list; spmpsci's .bbl defines \\doi with",
        "% \\providecommand, so this earlier definition wins and every DOI becomes https://doi.org/...",
        "\\providecommand{\\doi}[1]{\\url{https://doi.org/#1}}",
        "% Typography only (no content effect): svjour3's two-column measure (~8.4 cm) is 5% narrower",
        "% than IEEEtran's and the class sets no emergency stretch, so the untouched CAS body produced",
        "% ~190 overfull lines. microtype + a modest emergency stretch + hyphenation inside \\texttt",
        "% bring it back to the IEEE port's level.",
        "\\usepackage{microtype}",
        "\\usepackage[htt]{hyphenat}",
        "\\setlength{\\emergencystretch}{2.5em}",
        "\\tolerance=2000",
        "\\journalname{" + JOURNAL + "}",
        "\\begin{document}",
        "\\title{" + title + "}",
        "\\titlerunning{Candidate Comparability Before Promotion}",
        "\\author{" + names + "}",
        "\\authorrunning{" + _short(authors[0]["name"]) + " et al.}",
        "\\institute{" + short_names + " \\at",
        "  " + affiliation + "\\\\",
        "  \\email{" + emails + "}\\\\",
        "  ORCID: " + orcids,
        "}",
        "\\date{Received: date / Accepted: date}",
        "\\maketitle",
        "\\begin{abstract}",
        abstract,
        "\\keywords{" + " \\and ".join(keywords) + "}",
        "\\end{abstract}",
        "",
    ])

    # ---- Springer tail: Statements and Declarations + numbered bibliography -----------
    tail = "\n".join([
        "",
        "\\section*{Statements and Declarations}",
        "\\paragraph{Funding} " + funding,
        "",
        "\\paragraph{Competing interests} " + competing,
        "",
        "\\paragraph{Ethics approval and consent to participate} Not applicable: the study uses "
        "three public benchmark datasets and involves no human participants or animals.",
        "",
        "\\paragraph{Data availability} " + data,
        "",
        "\\paragraph{Code availability} The source code, frozen protocols, experiment runner and "
        "analysis scripts are part of the Zenodo artifact identified under Data availability.",
        "",
        "\\paragraph{Author contributions} " + contributions,
        "",
        "\\paragraph{Generative AI and AI-assisted technologies} " + ai_use,
        "",
        "\\bibliographystyle{spmpsci}  % Springer numbered style for mathematics/CS journals (keeps article titles;",
        "                              % the spphys.bst shipped in the IJIS zip is APS-style and drops them)",
        "\\bibliography{references}",
        "\\end{document}",
        "",
    ])

    out = head + body + tail
    (MS / "main_springer.tex").write_text(out, encoding="utf-8", newline="\n")
    print(f"main_springer.tex rebuilt from main.tex: {len(out.splitlines())} lines, "
          f"{len(keywords)} keywords, {len(authors)} authors")


if __name__ == "__main__":
    main()
